# This is a basic workflow to help you get started with Actions

name: Running a Python Scripts

# Controls when the workflow will run
on:
  schedule:
    # UTC时间4点，刚好是北京时间12点，开始运行
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装 git,和 urllib3,解决 MaxRetryError 错误。
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install git
        git clone https://github.com/urllib3/urllib3.git
        cd urllib3
        git checkout 1.26.x
        pip install .

    - name: 安装依赖。
      run: pip install requests

    - name: 显示 Python和 pip 的版本号,安装的包。
      run: |
        python --version
        pip --version
        pip list
    - name: 扫场所码
      env:
        Token: ${{ secrets.Token }}
      run: python scanRoomCode.py
